- name: Setup Redis repo
  ansible.builtin.copy:
    src: nodejs.repo
    dest: /etc/yum.repos.d/nodejs.repo

- name: Install Redis
  ansible.builtin.yum:
    name: redis
    state: installed

- name: Update Redis config file
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: "127.0.0.1"
    replace: "0.0.0.0"
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.conf

- name: Start redis service
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes