- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: Download database code
  import-role:
    name: common
    tasks_from: download

- name: Remove previous Content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Copy Roboshop content
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Start Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes