- name: Install Golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: Setup App User and App code
  ansible.builtin.import_role:
    name: common
    tasks_from: download

- name: Install {{COMPONENT}} Dependencies
  ansible.builtin.shell: go mod init {{COMPONENT}} && go get && go build
  args:
    chdir: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: Configure systemd for {{COMPONENT}}
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd

