- name: Set Host name
  ansible.builtin.shell: set-hostname {{COMPONENT}}

- name: Install Prometheus Node Exporter
  shell: curl https://github.com/KolaNeelakanteswararao/labautomation/blob/master/tools/prometheus-node-exporter/install.sh | bash
  when: APPTYPE == "app" or APPTYPE == "web"