- name: Setup repo file for NodeJs
  ansible.builtin.copy:
    src: nodejs.repo
    dest: /etc/yum.repos.d/nodejs.repo

- name: Install Nodejs
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: Setup App User and App code
  ansible.builtin.import_role:
    name: common
    tasks_from: download

#- name: Install {{COMPONENT}} Dependencies
#  community.general.npm:
#    path: /home/roboshop/{{COMPONENT}}
#  become_user: roboshop

- name: Install {{COMPONENT}} Dependencies
  shell: cd /home/roboshop/{{COMPONENT}} && npm install
  become_user: roboshop

- name: Configure systemd for {{COMPONENT}}
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd