route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
  - name: "email"
    email_configs:
      - to: "${neelakanta554@gmail.com}"      # you@example.com
        from: "${neelakanta554@gmail.com}"  # alertmanager@example.com
        smarthost: "email-smtp.us-east-1.amazonaws.com:587"
        auth_username: "{{SES_USER}}"
        auth_password: "{{SES_PASS}}"
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
